name: CI CD

on:
  push:
    branches: [ "CICD_test" ]

#  pull_request:
#    branches: [ "main" ]

jobs:
  #build:
  Build_MacOs:

    #runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      #with:
      #  submodules: 'recursive'
      #  token: ${{ secrets.ACCESS_TOKEN }}
    - name: see env
      run: echo $secrets
    #- name: Download Libtorch
    #  run: ./downloadLastestLibtorch.sh
#    - name: Checkout submodules using a PAT
#      run: |
#        git config --file .gitmodules --get-regexp url | while read url; do
#        git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
#        done
#        git submodule sync
#        git submodule update --init --recursive
#    - name: generate xcode 
#      run: cmake -DCMAKE_PREFIX_PATH=./libtorch -B Builds -G Xcode
#    - name: build all target
#      run: cmake --build Builds --config Release
