name: C/C++ CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download_Libtorch
      run: ./downloadLastestLibtorch.sh
    - name: generate xcode 
      run: cmake -DCMAKE_PREFIX_PATH=./libtorch -B Builds -G Xcode
    - name: build all target
      run: cmake --build Builds --config Release
