name: Testing

on:
  push:
    branches: [ "main",  "staging"]

jobs:

  testing:
    name: Run Tests
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest] Not windows yet
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_suffix: Ubuntu
          - os: macos-latest
            release_suffix: MacOs
#          - os: windows-latest
#            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
        ##Checkout submodules
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: 'recursive'

      - name: Install Prerequisites Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libasound2-dev

      - name: Download Libtorch Linux
        if: matrix.os == 'ubuntu-latest'
        run: wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcpu.zip

      - name: Download Libtorch MacOs
        if: matrix.os == 'macos-latest'
        run: wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.11.0.zip

#      - name: Download Libtorch Windows
#        if: matrix.os == 'windows-latest'
#        run: wget -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.11.0%2Bcpu.zip

      - name: Unzip it
        run: unzip libtorch.zip

      - name: Generate targets
        run: cmake -B Builds

      - name: build all target
        run: cmake --build Builds --config Release

      - name: Running tests
        run: ./Builds/Tests